name = "MDTools"
uuid = "2ac7dc56-4940-424b-bb1c-27afe2b7a90d"
authors = ["Sam"]
version = "0.1.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"

[targets]
test = ["Test", "Chemfiles"]
